In [41]:
import numpy as np
import pandas as pd

In [3]:
# How to create an Empty and Full numpy array
# Empty
l1=[]
arr1=np.array(l1)
print(arr1)

# Full
arr2 = np.full([3,4],1)
print(arr2)

# Explanation :-
# An empty array is an array that has no value or is null.
# We can use the empty array later to append the values or modify them.

[]
[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


In [4]:
# Create numpy array filled with all Zeros
arr3=np.zeros([3,4])
print(arr3)

# Explanation:-
# The numpy.zeros() function returns a new array of given shape and type, with zeros.

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [5]:
# Create numpy array filled with all Ones
arr4 = np.ones([4,5])
print(arr4)

# Explanation:-
# ones() function returns a new array of given shape and data type, where the element's value is set to 1.
# This function is very similar to numpy zeros() function.

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [6]:
# Check whether a numpy Array contains specified rows
a1=[  [1,2,3],
      [4,5,6],
      [7,8,9]]
arr6=np.array(a1)
lst=[4,5,7]
lst1=[4,5,6]

print(lst in  arr6.tolist())
print(lst1 in  arr6.tolist())
# Explanation:-
# If the given list is present in a NumPy array as a row then the output is True else False.
# The list is present in a NumPy array means any row of that numpy array matches with the given 
# list with all elements in given order

False
True


In [7]:
# How to remove non-numeric rows from numpy array
arr9=np.array([[1,2,3],
              [4,np.nan,5],
              [6,7,np.nan],
              [7,2,5],
              [8,9,np.nan]])
print(arr9)
arr9[np.all(~np.isnan(arr9),axis=1)]

# axis 1=Row wise, 0=Column wise in whole array

# Explanation :- 
# Many times we have non-numeric values in NumPy array. These values need to be removed, so that array
# will be free from all these unnecessary values and look more decent. 
# It is possible to remove all rows containing Nan values using the Bitwise NOT operator and np. isnan() function.

[[ 1.  2.  3.]
 [ 4. nan  5.]
 [ 6.  7. nan]
 [ 7.  2.  5.]
 [ 8.  9. nan]]


array([[1., 2., 3.],
       [7., 2., 5.]])

In [8]:
# remove a single-dimentional entries from shape of an array
arr7=np.array(
    [[[0],
     [1],
     [2]]]
)
arr8=np.squeeze(arr7)
arr8

# Explanation :-
# squeeze() function is used to remove single-dimensional entries from the shape of an array. 
# It returns an array with the same data but reshaped dimensions. 
# This function can be used to reduce the dimensions of an array, 
# which is useful for data preprocessing in machine learning applications.

array([0, 1, 2])

In [23]:
# Find the number of accurences of a sequence in numpy array 
arrr1=np.array([1,2,3,4,5,3,4,6,7,3,4])

repr(arrr1).count("3, 4")


3

In [47]:
# Find the most frequent value in numpy array 
arr10=np.array([1,2,2,6,4,5,6,6,6,7,8,9,9,9,0,11,12,33,44,44,44,0])
mode=np.bincount(arr10)
mode1=np.argmax(mode)
print(mode1)

# Explanation :- 
# in above .bincount() function is used to count the occurence of each element in array
# .argmax() mathod to get a value having a maximum value of occurence(Frequency)

6


In [72]:
# Combining a one and two-dimensional numpy array
ar1=np.array([[1,2,3,4],
              [11,22,33,44]])
ar2=np.array([69,68,67,44])

ar1.shape
ar2=ar2.reshape(1,4)

ar3=np.concatenate((ar1,ar2),axis=0)
ar3

# Explanation :- 
# First thing we have to get the shape of all array and then we have to reshape by same dimensions
# after that we can use .concatenate() function to combine two arrays.

array([[ 1,  2,  3,  4],
       [11, 22, 33, 44],
       [69, 68, 67, 44]])

In [91]:
# How to build an array of all combinations of two Numpy arrays?

arr12=np.array([1,2])
arr13=np.array([5,6])

arr14=np.array(np.meshgrid(arr12,arr13)).T.reshape(-1, 2)
print(arr14)

[[1 5]
 [1 6]
 [2 5]
 [2 6]]


# Numpy
## Functions

NumPy is a general-purpose array-processing package. It provides a high-performance multidimensional array object and tools for working with these arrays.

###### numpy.Squeeze()
###### numpy.unique()
###### numpy.asmatrix()
###### numpy.delete()
###### numpy.insert()

# 1. Function = np.squeeze()

In [13]:
fn1= np.array([[[1,2],[3,4]]])
ans = np.squeeze(fn1)
print(ans)

[[1 2]
 [3 4]]


squeeze() function is used to remove single-dimensional entries from the shape of an array. 
It returns an array with the same data but reshaped dimensions. 
This function can be used to reduce the dimensions of an array, 
which is useful for data preprocessing in machine learning applications.

# 2. Function = np.unique()

In [14]:
fn2 = np.array([1,2,2,2,3,4,5,5])
ans = np.unique(fn2)
print(ans)

[1 2 3 4 5]


The numpy. unique() function finds the unique elements of an array and returns these unique elements as a sorted array.

# 3. Function=np.asmatrix()

In [23]:
fn3 = np.array([[1,2,3],[4,5,6]])
m=np.asmatrix(fn3)
fn3[0,0]=0
m[1,0]=200
print(fn3)
print("\n",m)

[[  0   2   3]
 [200   5   6]]

 [[  0   2   3]
 [200   5   6]]


 Returns a matrix by interpreting the input as a matrix.
 whenever you try to change value of one array it will automatically change in matrixed array.

# 4. Function = np.delete()

In [30]:
fn4 =np.arange(1,16).reshape(3,5)
ans= np.delete(fn4,1,0)
print(fn4)
print("\n",ans)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]

 [[ 1  2  3  4  5]
 [11 12 13 14 15]]


The numpy. delete() function returns a new array with the deletion of sub-arrays along with the mentioned axis.

# 5. Function = np.insert()

In [32]:
fn5 = np.arange(1,21).reshape(4,5)
ans=np.insert(fn5,2,0)
print(ans)

[ 1  2  0  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


The NumPy insert() function inserts a value/values along the specified axis at a given index.

In [40]:
fn5 = np.arange(1,26).reshape(5,5)
fn6=np.arange(26,31).reshape(1,5)
ans=np.insert(fn5,4,fn6, axis=1)
print(ans)

[[ 1  2  3  4 26  5]
 [ 6  7  8  9 27 10]
 [11 12 13 14 28 15]
 [16 17 18 19 29 20]
 [21 22 23 24 30 25]]
